### ISSUE TITLE
Check in & Check Outs

### ISSUE THREAD

**Issue by iamtutumo** [OCA/vertical-hotel#10]
There is no facility to make a check in and check out for example if a guest books for 5 days and they leave after 2 days , we should check them out such that the room is marked as available

**Comment by JayVora-SerpentCS** [comment]
We have the chckout dates now. We are editing the checkout logic in #OCA2017. Thanks.

**Comment by sound675** [comment]
Hi JayVora-SerpentCS,

Excuse me for opening this ticket again,
I am using Odoo 12 CE

I am unable to check out the guest from the rooms, thus all the rooms status is always will be "Occupied"

I have to manually checklist the room status from Configuration - Rooms, in order to change the status.

Hope to get your feedback about the logic in #OCA2017 that you mentioned earlier.

Thank you

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs Can you take a look?
Thanks.
