### ISSUE TITLE
While try to install addon Hotel Management apps getting following error in odoo v9

### ISSUE THREAD

**Issue by ebaseitsolution** [OCA/vertical-hotel#11]
ParseError: "Invalid view definition

Error details:
Element '<xpath expr="//div[@name='company_address']">' cannot be located in parent view

Error context:
View `report.external_layout_header`
[view_id: 176, xml_id: report.external_layout_header, model: n/a, parent_id: n/a]
None" while parsing None:9, near
<data inherit_id="report.external_layout_header" primary="True">
            <xpath expr="//div[@name='company_address']" position="after">
                <div class="col-xs-4 pull-right" name="right_box">
                    <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 100)" style="width:300px;height:50px;"/>
                </div>
            </xpath>
        <xpath position="attributes" expr="."><attribute name="t-name">stock.external_layout_header_barcode_right</attribute></xpath></data>

Any help will be highly appreciated

**Comment by elicoidal** [comment]
Hi,
this module has not yet been ported to v9.
best regards

**Comment by ebaseitsolution** [comment]
Hi Eric,

Thanks a lot for your reply. Can you guide me what exactly I have to perform to install this add on apps/ module in Odoo V9.

Regards
Snigdha Bhattacharya

**Comment by elicoidal** [comment]
@ebaseitsolution 
Addons are valid mostly for one version of Odoo. Today to be able to use this module in v9 you need first to migrate it to the new version. This means some programming to change the data structure and methods before you are able to use it properly.
Migration is quite a technical process and might imply efforts from several community members.
You can participate in the task if you understand it (any help is welcome!) and otherwise you will have to wait until some contributor publish the migrated v9 module.
I hope this is clear and in the meantime, I suggest you follow the repository for update.

Have a nice day

**Comment by ebaseitsolution** [comment]
I have downloaded the addon modules from Github repository as per the odoo version. I am the facing the installation issue in both V8 and V9. I have used the version based addon apps. If I could get the error resolution I will try to apply the necessary changes. Currently I can't find similar error in the community.
