### ISSUE TITLE
Hotel Management

### ISSUE THREAD

**Issue by Osvalcosta** [OCA/vertical-hotel#46]
I am testing hotel management module and i am getting error while doing the checking,
Saying that the time must be greater than the corrent time, but my time is corret.

Can some please help me how to fix it ??

**Comment by pedrobaeza** [comment]
Please Odoo version and detailed steps to reproduce the problem.

**Comment by rbetancor** [comment]
That happens to me also, the reason is that CheckIn field is allways filled with current date and time and when you finish filling the other fields and send the data to the server ,the time part of the CheckIn field is way seconds/minutes in the past and the server refuses the whole record.

The only way to bypass this, is to put some minutes more on the time part of the field, till someone fixes this on the code.

**Comment by JayVora-SerpentCS** [comment]
@nikul-serpentcs
